name: Java CI (JUnit)
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Run-tests:
    runs-on: ubuntu-latest

    steps:
#      - run: echo "ğŸ‰ Start preparing for tests..."
#      - name: Check out repository code
      - uses: actions/checkout@v4

#      - name: Set up JDK
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

#      - run: echo "ğŸ’¡ The JDK is ready for use!"
      - name: Build and test with Maven
        run: mvn test

#      - run: echo "ğŸ All tests passed!"
